<form method="get" action="<?php echo $registerCardUrl ?>">
<?php echo $saferPayRequestParams ?>
Kartennummer <input type="text" name="sfpCardNumber" value="9451123100000004"/><br/>
Kartengültigkeit <input type="text" name="sfpCardExpiryMonth" value="11" maxlength="2"/>
<input type="text" name="sfpCardExpiryYear" value="2013" maxlength="4"/><br/>
<input type="submit" value="Registrieren..."/>
</form>